[Map and Set] 과제 제출
Altu-Bitu/Altu-Bitu-minji pull request #2
Opened 2021-09-10 08:22 UTC by nitronium102

2021-09-10 08:32 UTC, nitronium102 commented on [Map and Set] 0907/assignments/18870.cpp
> +// 즉 해당 값보다 작은 값들의 개수
ios::sync with studio, cin::tie까지 썼는데도 시간 초과가 나거나 제한 시간과 딱 맞게 통과하는데 여기에서 더 시간을 줄일 수 있는 방법이 있을까요...?

2021-09-10 08:36 UTC, nitronium102 commented on [Map and Set] 0907/assignments/2015.cpp
> +        m[p_sum[i]]++;
(2015번 수들의 합 4) 나름대로 로직을 짜보았는데 예시를 넣어보면 4 대신 2가 나오더라고요! 혼자서 고쳐보려 했는데 아무리 봐도 잘 모르겠어서....혹시 어느 부분이 잘못된 건지 알 수 있을까요?😢

2021-09-10 09:14 UTC, HyunJiLim0406 requested changes
p3(2015 제외)
아직 못푸신 2015번 제외하고는 코드들이 너무 완벽해서 제가 할 말이 없네요 하핳
18870번은...저희도 준비하면서 시간때문에 애먹었던 문제예요. 지금 코드도 좋은 코드입니다!

코드에 달린 코멘트들 확인해주시구요! 제가 드린 힌트 잘 생각해보세요~
문제 푸신 뒤에 다시 저 리뷰어로 호출해주세요 화이팅!

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/10757.cpp
> +    }
digit%10은 10미만이라 굳이 to_string을 사용할 필요는 없어요

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/10757.cpp
> +
리버스 함수를 사용하는 것도 좋지만 시간복잡도면에서는 그냥 맨 뒤에서부터 거꾸로 출력하는게 더 좋을 수도 있어요!
물론 이것도 아주 좋은 방법입니다.

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/10757.cpp
> +int main(){
아주 잘 푸셨습니다! 특히 string을 크게 가공하지 않고 사용해서 연산 횟수를 많이 줄이셨네요~!

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/1764.cpp
> +    map<string, bool> name;
꼭 map을 사용해야할까요? 다른 방법도 있어요!

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/18870.cpp
> +// 즉 해당 값보다 작은 값들의 개수
이 문제가 원래 시간 제한이 빡빡해요! 아주 잘 푸셨습니다

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/18870.cpp
> +        rank[x]; // map에 key 넣어줌(자동 정렬)
그래도 rank[x]를 아무 값이라도 초기화 해주는게 좋아요!

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/18870.cpp
> +        rank[x]; // map에 key 넣어줌(자동 정렬)
제 생각에 이 문제가 시간초과인 이유는 rank가 두 번 갱신되기 때문인 것 같아요! (추측)
(이 문제가 그만큼 시간면에서 까딸스러워요)
첫번째 풀이로 잘 푸셨고 더 개선할 수 있는 부분은 없는 듯해요!

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/19636.cpp
> +            basic2 += (double)floor((d_input - (basic2 + d_output))/2.0);
👍 고생많으셨어요

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/2015.cpp
> +        m[p_sum[i]]++;
p_sum[i]가 k와 같은 경우엔 어떻게 되나요?
그리고 반례가 하나 더 보이네요! 과연 int 범위를 넘어가는게 cnt 뿐일까요?

2021-09-10 09:14 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/9375.cpp
> +            cloth[type]++;
좋아요! name은 필요가 없죠~!

2021-09-12 03:19 UTC, HyunJiLim0406 reviewed
p3
리뷰가 늦어졌네요ㅠㅠ 죄송합니다
만약 제가 다음에도 또 이렇게 늦으면 알림을 확인하지 못한거니까 슬랙 멘션등으로 알려주세요!
코드 다 좋구요 merge해도 좋아요!
쿠폰 기록해두겠습니다~ 과제하느라 수고많으셨습니다!!

2021-09-12 03:19 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/10757.cpp
> +        ans += digit%10 + '0'; // to_string 사용 X
👍

2021-09-12 03:19 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/1764.cpp
> +    set<string> name; // map보다 빨라짐!(20ms)
👍

2021-09-12 03:19 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/2015.cpp
> +
👍

2021-09-12 03:19 UTC, HyunJiLim0406 commented on [Map and Set] 0907/assignments/2015.cpp
> +
👍

2021-09-12 12:11 UTC, merged